### ISSUE TITLE
set active user, & create user

### ISSUE THREAD

**Issue by RSiimon** [raultolp/IEX#2]
Set active useri valimisel prinditakse olemasolevate userite nimed. Kui nende seast üks valida, siis prindib muuhulgas, et "Name already exists!", ** mida ei peaks tegema:** 

`test2.game / Active user: tim> 4`
`Defined users:   tim          betty`
`Enter user name: betty`
`Name already exists!`  <--   **NB!**
`User betty is now active.`

Uue kasutaja loomisel, kui sisestada juba olemasolev kasutajanimi, siis prindib:
`test2.game / Active user:betty> 1`
`Enter user name: tim`
`Name already exists!`   <--   **NB!**
`Created user:  tim`  <--   **NB!**

ning lisab teise sama nimega kasutaja kasutajate listi. Tulemuseks on, et **kasutajate listis on kaks sama nimega kasutajat**.

**Comment by helenarebane** [comment]
See on tegelikult teadaolev probleem, millega keegi pole jõudnud tegeleda.

**Comment by RSiimon** [comment]
Lihtsalt testisin veidi ja märkisin siia probleemid üles, et need meelest ei läheks

**Comment by raultolp** [comment]
fixed
