### ISSUE TITLE
Veergude formaatimine ShowUserTransactions ja ShowUserPortfolio väljatrükkides

### ISSUE THREAD

**Issue by RSiimon** [raultolp/IEX#4]
Praegu ei ole tehingute ja portfelli väljatrükkides veerud korrektselt joondatud. Joondamine tundus keeruline, sest veergudes olevad väärtused on erineva pikkusega stringid. 
Kui edasi plaanime minna FX peale, siis võib-olla ei ole see nii oluline.

**Comment by raultolp** [comment]
fixed
